version: '2'
services:
  web:
    image: ihsan:11
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - /var/lib/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:10
    env_file:
      - env_file.env
    volumes:
      - /var/lib/postgresql/data/pgdata